4958 adds description using `_desc_` in bundle config (#4963)
* adds new keyword

Signed-off-by: Wenqi Li <wenqil@nvidia.com>

* fixes #4962

Signed-off-by: Wenqi Li <wenqil@nvidia.com>

* fixes #4964

Signed-off-by: Wenqi Li <wenqil@nvidia.com>

* fixes tests

Signed-off-by: Wenqi Li <wenqil@nvidia.com>

* fixes typo

Signed-off-by: Wenqi Li <wenqil@nvidia.com>

Signed-off-by: Wenqi Li <wenqil@nvidia.com>

diff --git a/.github/workflows/pythonapp.yml b/.github/workflows/pythonapp.yml
--- a/.github/workflows/pythonapp.yml
+++ b/.github/workflows/pythonapp.yml
@@ -222,5 +222,6 @@ jobs:
         cd docs/
         make clean
         make html 2>&1 | tee tmp_log
+        if [[ $(grep -c "ERROR:" tmp_log) != 0 ]]; then echo "found errors"; grep "ERROR:" tmp_log; exit 1; fi
         if [[ $(grep -c "WARNING:" tmp_log) != 0 ]]; then echo "found warnings"; grep "WARNING:" tmp_log; exit 1; fi
       shell: bash
