setuptools fix
Signed-off-by: Eric Kerfoot <17726042+ericspod@users.noreply.github.com>

diff --git a/.github/workflows/setupapp.yml b/.github/workflows/setupapp.yml
--- a/.github/workflows/setupapp.yml
+++ b/.github/workflows/setupapp.yml
@@ -23,62 +23,63 @@ jobs:
   #   - docker-py3-pip- (shared)
   #   - ubuntu 37 38 39 310-pip-
   #   - os-latest-pip (shared)
-  coverage-py3:
-    # if: github.repository == 'Project-MONAI/MONAI'
-    if: ${{ false }}  # disable self-hosted job project-monai/monai#7039
-    container:
-      image: nvcr.io/nvidia/pytorch:22.04-py3
-      options: --gpus all
-    runs-on: [self-hosted, linux, x64, integration]
-    steps:
-    - uses: actions/checkout@v6
-    - name: cache weekly timestamp
-      id: pip-cache
-      run: |
-        echo "datew=$(date '+%Y-%V')" >> $GITHUB_OUTPUT
-    - name: cache for pip
-      if: ${{ startsWith(github.ref, 'refs/heads/dev') }}
-      uses: actions/cache@v5
-      id: cache
-      with:
-        path: |
-          ~/.cache/pip
-          ~/.cache/torch
-        key: docker-py3-pip-${{ steps.pip-cache.outputs.datew }}
-    - name: Install the dependencies
-      run: |
-        which python
-        python -m pip install --upgrade pip wheel wheel-stub
-        python -m pip install --upgrade torch torchvision
-        python -m pip install -r requirements-dev.txt
-    - name: Run unit tests report coverage
-      env:
-        NGC_API_KEY: ${{ secrets.NGC_API_KEY }}
-        NGC_ORG: ${{ secrets.NGC_ORG }}
-        NGC_TEAM: ${{ secrets.NGC_TEAM }}
-      run: |
-        python -m pip list
-        git config --global --add safe.directory /__w/MONAI/MONAI
-        git clean -ffdx
-        df -h
-        # python -m pip cache info
-        nvidia-smi
-        export CUDA_VISIBLE_DEVICES=$(python -m tests.utils | tail -n 1)
-        echo $CUDA_VISIBLE_DEVICES
-        trap 'if pgrep python; then pkill python; fi;' ERR
-        python -c $'import torch\na,b=torch.zeros(1,device="cuda:0"),torch.zeros(1,device="cuda:1");\nwhile True:print(a,b)' > /dev/null &
-        python -c "import torch; print(torch.__version__); print('{} of GPUs available'.format(torch.cuda.device_count()))"
-        python -c 'import torch; print(torch.rand(5, 3, device=torch.device("cuda:0")))'
-        BUILD_MONAI=1 ./runtests.sh --build --coverage --unittests --disttests  # unit tests with coverage report
-        BUILD_MONAI=1 ./runtests.sh --build --coverage --net  # integration tests with coverage report
-        coverage xml --ignore-errors
-        if pgrep python; then pkill python; fi
-      shell: bash
-    - name: Upload coverage
-      uses: codecov/codecov-action@v6
-      with:
-        fail_ci_if_error: false
-        files: ./coverage.xml
+
+  # coverage-py3:
+  #   # if: github.repository == 'Project-MONAI/MONAI'
+  #   if: ${{ false }}  # disable self-hosted job project-monai/monai#7039
+  #   container:
+  #     image: nvcr.io/nvidia/pytorch:22.04-py3
+  #     options: --gpus all
+  #   runs-on: [self-hosted, linux, x64, integration]
+  #   steps:
+  #   - uses: actions/checkout@v6
+  #   - name: cache weekly timestamp
+  #     id: pip-cache
+  #     run: |
+  #       echo "datew=$(date '+%Y-%V')" >> $GITHUB_OUTPUT
+  #   - name: cache for pip
+  #     if: ${{ startsWith(github.ref, 'refs/heads/dev') }}
+  #     uses: actions/cache@v5
+  #     id: cache
+  #     with:
+  #       path: |
+  #         ~/.cache/pip
+  #         ~/.cache/torch
+  #       key: docker-py3-pip-${{ steps.pip-cache.outputs.datew }}
+  #   - name: Install the dependencies
+  #     run: |
+  #       which python
+  #       python -m pip install --upgrade pip wheel wheel-stub
+  #       python -m pip install --upgrade torch torchvision
+  #       python -m pip install -r requirements-dev.txt
+  #   - name: Run unit tests report coverage
+  #     env:
+  #       NGC_API_KEY: ${{ secrets.NGC_API_KEY }}
+  #       NGC_ORG: ${{ secrets.NGC_ORG }}
+  #       NGC_TEAM: ${{ secrets.NGC_TEAM }}
+  #     run: |
+  #       python -m pip list
+  #       git config --global --add safe.directory /__w/MONAI/MONAI
+  #       git clean -ffdx
+  #       df -h
+  #       # python -m pip cache info
+  #       nvidia-smi
+  #       export CUDA_VISIBLE_DEVICES=$(python -m tests.utils | tail -n 1)
+  #       echo $CUDA_VISIBLE_DEVICES
+  #       trap 'if pgrep python; then pkill python; fi;' ERR
+  #       python -c $'import torch\na,b=torch.zeros(1,device="cuda:0"),torch.zeros(1,device="cuda:1");\nwhile True:print(a,b)' > /dev/null &
+  #       python -c "import torch; print(torch.__version__); print('{} of GPUs available'.format(torch.cuda.device_count()))"
+  #       python -c 'import torch; print(torch.rand(5, 3, device=torch.device("cuda:0")))'
+  #       BUILD_MONAI=1 ./runtests.sh --build --coverage --unittests --disttests  # unit tests with coverage report
+  #       BUILD_MONAI=1 ./runtests.sh --build --coverage --net  # integration tests with coverage report
+  #       coverage xml --ignore-errors
+  #       if pgrep python; then pkill python; fi
+  #     shell: bash
+  #   - name: Upload coverage
+  #     uses: codecov/codecov-action@v6
+  #     with:
+  #       fail_ci_if_error: false
+  #       files: ./coverage.xml
 
   test-py3x:
     runs-on: ubuntu-latest
@@ -96,11 +97,12 @@ jobs:
         cache: pip
     - name: Install CPU PyTorch
       run: |
+        python -m pip install --upgrade pip wheel wheel-stub
         python -m pip install torch==2.8.0 torchvision --extra-index-url https://download.pytorch.org/whl/cpu
     - name: Install the dependencies
       run: |
         find  /opt/hostedtoolcache/* -maxdepth 0 ! -name 'Python' -exec rm -rf {} \;
-        python -m pip install --no-build-isolation --upgrade pip wheel wheel-stub
+        python -m pip install --no-build-isolation -r requirements-min.txt  # necessary only here for some reason?
         python -m pip install --no-build-isolation -r requirements-dev.txt
     - name: Run quick tests CPU ubuntu
       env:
